/**
 * XIT001 API のキー → 日本語名称の対応表（全項目表の表示順）
 */
export const XIT001_COLUMN_LABELS: Record<string, string> = {
  PriceCategory: "価格情報区分",
  Type: "種別",
  Region: "地域区分",
  MunicipalityCode: "市区町村コード",
  Prefecture: "都道府県",
  Municipality: "市区町村",
  DistrictName: "地区名",
  TradePrice: "取引価格（総額）",
  PricePerUnit: "坪単価",
  FloorPlan: "間取り",
  Area: "面積（㎡）",
  UnitPrice: "㎡単価",
  LandShape: "土地形状",
  Frontage: "間口",
  TotalFloorArea: "延床面積",
  BuildingYear: "建築年",
  Structure: "構造",
  Use: "用途",
  Purpose: "目的",
  Direction: "方位",
  Classification: "道路種別",
  Breadth: "幅員（道路幅）",
  CityPlanning: "都市計画区分",
  CoverageRatio: "建蔽率",
  FloorAreaRatio: "容積率",
  Period: "取引時点",
  Renovation: "改装",
  Remarks: "備考",
  DistrictCode: "地区コード",
};

/** 表示順のAPIキー配列 */
export const XIT001_COLUMN_KEYS: string[] = [
  "PriceCategory",
  "Type",
  "Region",
  "MunicipalityCode",
  "Prefecture",
  "Municipality",
  "DistrictName",
  "TradePrice",
  "PricePerUnit",
  "FloorPlan",
  "Area",
  "UnitPrice",
  "LandShape",
  "Frontage",
  "TotalFloorArea",
  "BuildingYear",
  "Structure",
  "Use",
  "Purpose",
  "Direction",
  "Classification",
  "Breadth",
  "CityPlanning",
  "CoverageRatio",
  "FloorAreaRatio",
  "Period",
  "Renovation",
  "Remarks",
  "DistrictCode",
];
